### ISSUE TITLE
Restructure initialisation to match other XRInterfaces

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/TiltFiveGodot4#15]
This is absolutely a nitpicking issue and I'll find an hour somewhere to polish this up. Just recording this as something to remind me :)

The design of the XRServer is such that XRInterfaces are registered early, and the `initialize`/`uninitialize` function build up/tear down the system. For TiltFive its the other way around.

**Comment by patrickdown** [comment]
Part of the reason for this is that there is information passed into the T5 initialization functions, such and application ID and version. (Not 100% sure why but I expect it's for logging and customer support.) I was setting these up in scene nodes.  I could see putting this info into some sort of custom resource that could be loaded on startup. This would help in fixing this.

**Comment by patrickdown** [comment]
> This is absolutely a nitpicking issue and I'll find an hour somewhere to polish this up. Just recording this as something to remind me :)
> 
> The design of the XRServer is such that XRInterfaces are registered early, and the `initialize`/`uninitialize` function build up/tear down the system. For TiltFive its the other way around.

Part of the reason for this is that there is information passed into the T5 initialization functions, such and application ID and version. (Not 100% sure why but I expect it's for logging and customer support.) I was setting these up in scene nodes. I could see putting this info into some sort of custom resource that could be loaded on startup. This would help in fixing this.

**Comment by BastiaanOlij** [comment]
> Part of the reason for this is that there is information passed into the T5 initialization functions, such and application ID and version. (Not 100% sure why but I expect it's for logging and customer support.) I was setting these up in scene nodes. I could see putting this info into some sort of custom resource that could be loaded on startup. This would help in fixing this.

We already store some of this information in the project settings and can retrieve it from there. I still need to look into the version number however because that is specified in export settings.

I'll take care of this one when I have a free moment :)
