### ISSUE TITLE
Introduce our own camera class for glasses

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/TiltFiveGodot4#16]
To correctly place the camera node in the world `XRCamera3D` binds itself to the head tracker (which is missing from the plugin). Other than that its near and far is used when rendering. In Godot 3 it had further functionality that has now been removed so it doesn't do that much more than the normal camera, all the real magic happens in the XRInterface.

So for correctly placing the camera nodes we could introduce trackers for each glasses and create a `T5Camera3D` node that simply inherits `Camera3D`, binds to the correct tracker and updates its position accordingly.

Whether this will have a lot of benefit I don't know, it doesn't seem common for the form factor to have elements childed to the glasses, but it will allow us to show glasses (optionally) in a spectator view.

**Comment by patrickdown** [comment]
PR #23 takes care of this
