### ISSUE TITLE
Big oops in swap chain and other issues.

### ISSUE THREAD

**Issue by patrickdown** [GodotVR/TiltFiveGodot4#22]
https://github.com/GodotVR/TiltFiveGodot4/blob/11eedc20c351fcaf35a35eecdbbcb7fb6511a28c/extension/T5Integration/Glasses.cpp#L544-L562

There is a bug here that is actually producing better looking results.

These lines revel a bug where the system was not advancing though the swap chain. the line  `_current_frame_idx = (_current_frame_idx + 1) % _swap_chain_frames.size();` really needs to be moved to just under the `t5SendFrameToGlasses` call. 

I did try this fix but discovered that weird tracking distortions appeared in the Vulkan output. I'm not sure what the problem is yet. It could be that something about this config is fighting with the predictive pose estimation in the glasses or it could be that we need to set up some Vulkan barrier before submitting the frames. 

So as it stands only one frame in the swap chain is being used and that bug actually produces the best results under Vulkan. There is still some small jitter in the Vulkan output so it seems there is still some sort of problem there.

**Comment by BastiaanOlij** [comment]
Could indeed be a timing issue, as you're doing a texture copy, that copy won't have completed when you're submitting.

Do we still need to do the copy? Aren't arrays implemented for Vulkan now as well?
