### ISSUE TITLE
IPD issues with world_scale

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/TiltFiveGodot4#34]
One of the issues I seem to have run into while streaming, though I could be wrong, is that when I changed world scale the IPD seemed wrong.

I'll investigate more soon

**Comment by patrickdown** [comment]
I haven't noticed this. The code for it looks right to me.

**Comment by BastiaanOlij** [comment]
I think this may have been a problem on my end. I think one of my glasses is simply acting up.. It only happens sporadically

**Comment by patrickdown** [comment]
Let's close this for now. We can open again if we can find something solidly reproducable.
