### ISSUE TITLE
Add signals when glasses scene is added/removed

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/TiltFiveGodot4#35]
Will be experimenting with this more but one thing I really missed was a way to react when a glasses scene was added and/or removed. We should probably emit a signal from the T5 manager.

We also need to look into easier ways for the glasses scene to communicate with the main playing logic.

**Comment by patrickdown** [comment]
Does [this](https://github.com/patrickdown/TiltFiveGodot4/tree/add_scene_signals) look like the right direction @BastiaanOlij ?

**Comment by BastiaanOlij** [comment]
Yes that looks very good!
