### ISSUE TITLE
Exporting project as binary with the entension enabled

### ISSUE THREAD

**Issue by kcf-jackson** [GodotVR/TiltFiveGodot4#50]
Thank you for creating the GDExtension for the Tilt Five glasses. It is working great!

How do you export the project with the extension enabled? The extension works fine in development mode, but when I export the project and run the binary file, the rendering does not happen with the glasses. The same happens with and without the "debug" export option. Thanks.

**Comment by BastiaanOlij** [comment]
We need to look into that, it's probably forgetting to exporting the necessary dlls along. Might be something missing in the `.gdextension` file.

You can probably manually copy the files next to the exe and see if that makes it work, it should include the `TiltFiveNative.dll` and `libgdtiltfive.windows.template_debug.x86_64.dll`/`libgdtiltfive.windows.template_release.x86_64.dll`.

**Comment by kcf-jackson** [comment]
Yes, it works! Previously the `TiltFiveNative.dll` was missing. I copied it from `addons/tiltfive/bin` folder, and it fixed the issue. Many thanks.

**Comment by patrickdown** [comment]
Reopening because we need to investigate the reason the native library is not being copied.
